foot_market/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import landing, home, donations

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home, name='home'),
    path('', home, name='default'),
    path('landing/', landing, name='landing'),
    path('donations/', donations),
    path('player/', include('player.urls')),
    path('trade/', include('trade.urls')),
    path('ipo/', include('ipo.urls')),
    path('user/', include('user.urls'))
]

ipo/urls.py
from django.urls import path

from .views import (IpoListView,
                    IpoBidCreateView,
                    IpoBidDeleteView,
                    IpoBidUpdateView,
                    IpoCloseView
                    
)

app_name = 'ipo'
urlpatterns = [
    path('ipo_list/', IpoListView.as_view(), name='ipo-list'),
    path('<int:id>/ipo_bid/', IpoBidCreateView.as_view(), name='ipo-bid'),
    path('<int:id>/ipo_delete/', IpoBidDeleteView.as_view(), name='ipo-delete'),
    path('<int:id>/ipo_update/', IpoBidUpdateView.as_view(), name='ipo-update'),
    path('<int:id>/ipo_close/', IpoCloseView.as_view(), name='ipo-close')
    
]

user/urls.py
from django.urls import path
from .views import (UserRegisterView,
    UserOverviewView,
                    LoginView,
                    LogoutView,
                    UserHistoryView
)

app_name = 'user'
urlpatterns = [
    #path('', CourseView.as_view(template_name='contact.html'), name='courses-list'),
    #path('', my_fbv, name='courses-list'),
    #path('<int:id>/', CourseView.as_view(), name='courses-detail'),
    #path('', CourseListView.as_view(), name='courses-list'),
    #path('', MyListView.as_view(), name='courses-list'),
    #path('create/', CourseCreateView.as_view(), name='courses-create'),
    #path('<int:id>/update/', CourseUpdateView.as_view(), name='courses-update'),
    #path('<int:id>/delete/', CourseDeleteView.as_view(), name='courses-delete'),
    path('user_register/', UserRegisterView.as_view(), name='user-register'),
    path('user_overview/', UserOverviewView.as_view(), name='user-overview'),
    path('user_history/', UserHistoryView.as_view(), name='user-history'),
    path('user_login/', LoginView.as_view(), name = 'user-login'),
    path('user_logout/', LogoutView.as_view(), name = 'user-logout')
]

user/models.py
from django.db import models
#from django.conf import settings
#from django.contrib.auth.models import User
#from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

from player.models import Player

from .managers import CustomUserManager
# Create your models here.
#User = get_user_model()

class CustomUser(AbstractUser):
    #username = models.CharField(max_length=40, unique=True)
    #email = models.EmailField(_('email address'), unique=True)
    age = models.IntegerField(default=0)
    funds = models.IntegerField(default=0)

    #objects = CustomUserManager()

    #USERNAME_FIELD = 'username'
    #EMAIL_FIELD = 'email'
    #REQUIRED_FIELDS = ['email']

    def __str__(self):
        return (f'{self.username}')

    def get_funds(self):
        return self.funds   

    def set_funds_variation(self, amount):
        self.funds = self.funds + amount
        self.save()

    def get_user(self):
        return self

#if i have to lookup for a model and the foreign key is in the other model, i just have to: 'portfolio_set' instead of the model -> queryset
class Portfolio(models.Model):
    id = models.AutoField(primary_key=True)
    player = models.ForeignKey(Player, on_delete=models.SET_NULL, null=True, blank=False)
    count = models.IntegerField(default = 0)
    compromised = models.IntegerField(default = 0)
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=False)
    #value_total = models.IntegerField(default=get_value_total())

    def add_count(self):
        self.count = self.count + 1
        self.save()

    def sub_count(self):
        if (self.count - self.compromised - 1) < 0:
            raise ValueError("You don't have enough assets.")
        else:
            self.count = self.count - 1
            self.save()
    
    def check_count(self):
        if (self.count - self.compromised - 1) < 0:
            return False
        else:
            return True

    def add_compromised(self):
        self.compromised = self.compromised + 1
        self.save()

    def sub_compromised(self):
        self.compromised = self.compromised - 1
        self.save()

    def get_value_total(self):
        return self.player.price_actual*self.count

    def get_value_actual(self):
        return self.player.price_actual
    
    def get_value_last(self):
        return self.player.price_last

    def get_value_percentege(self):
        return ((self.player.price_actual-self.player.price_last)/self.player.price_last)*100

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class UserModelForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'age'
        ]
        widgets = {'funds': forms.HiddenInput(),
        'status': forms.HiddenInput()}

    #Validación en el form y no en el video
    def clean_value(self):
        value = self.cleaned_data.get('value')
        if value == int:
            raise forms.ValidationError("This is not a valid value")
        return value

class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    age = forms.IntegerField(required=True)
    funds = forms.IntegerField(required=False,widget=forms.HiddenInput())

    class Meta:
        model = CustomUser
        #fields = ("username","first_name","last_name", "email", "age", "password1", "password2","funds")
        fields = ("username","first_name","last_name", "email", "age","funds")
        #widgets = {'funds': forms.HiddenInput()}

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        first_name = self.cleaned_data["first_name"]
        last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        user.age = self.cleaned_data["age"]
        user.funds = self.cleaned_data["funds"]
        if commit:
            user.save()
        return user

class UserChangeForm(UserChangeForm):
    age = forms.IntegerField(required=False)
    funds = forms.IntegerField(required=False)

    class Meta:
        model = CustomUser
        #fields = ("username","first_name","last_name", "email", "age", "password1", "password2","funds")
        fields = ("username","first_name","last_name", "email", "age","funds")

user/views.py
from django.shortcuts import render, get_object_or_404, redirect
#from django.contrib.auth.decorators import login_required
#from django.contrib.admin.views.decorators import staff_member_required
from django.views import View

from .models import CustomUser, Portfolio
from ipo.models import Bidder
from trade.models import Bid, Ask 
#from .forms import UserModelForm
#---------------------------------------
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView
#---------------------------------------
from .forms import UserCreateForm 
# Create your views here.

user_initial_funds = 100000000

class CustomUserObjectMixin(object):
    model = CustomUser

    def get_object(self):
        id = self.kwargs.get('id')
        obj = None
        if id is not None:
            obj = get_object_or_404(self.model, id=id)
        return obj

#@staff_member_required
#@login_required
class UserOverviewView(View):
    template_name = "user_overview.html"

    def get_portfolio_queryset(self, request):
        queryset = Portfolio.objects.filter(user__id = request.user.id)
        return queryset

    def get_bidder_queryset(self, request):
        queryset = Bidder.objects.filter(bidder__id = request.user.id).order_by('-date_created')
        return queryset

    def get_bid_queryset(self, request):
        queryset_bid = Bid.objects.filter(owner__id = request.user.id).order_by('-date_created')
        return queryset_bid
        
    def get_ask_queryset(self, request):
        queryset_ask = Ask.objects.filter(owner__id = request.user.id).order_by('-date_created')
        return queryset_ask

    def get(self, request, *args, **kwargs):
        context = {'portfolio': self.get_portfolio_queryset(request),
                    'bidder':self.get_bidder_queryset(request),
                    'bid':self.get_bid_queryset(request),
                    'ask':self.get_ask_queryset(request)}
        return render(request, self.template_name, context)

class UserHistoryView(View):
    template_name = "user_history.html"

    def get_bidder_queryset(self, request):
        queryset = Bidder.objects.filter(bidder__id = request.user.id).exclude(status='Set')
        return queryset

    def get_bid_queryset(self, request):
        queryset_bid = Bid.objects.filter(owner__id = request.user.id).exclude(status='Set')
        return queryset_bid
        
    def get_ask_queryset(self, request):
        queryset_ask = Ask.objects.filter(owner__id = request.user.id).exclude(status='Set')
        return queryset_ask

    def get(self, request, *args, **kwargs):
        context = {'bidder':self.get_bidder_queryset(request),
                    'bid':self.get_bid_queryset(request),
                    'ask':self.get_ask_queryset(request)}
        return render(request, self.template_name, context)

#class UserRegisterView(View):
#    template_name = "user_register.html" #DetailView

#    def get(self, request, *args, **kwargs):
#        # GET method
#        form = UserModelForm()
#        context = {"form": form}
#        return render(request, self.template_name, context)
#    
#    def post(self, request, *args, **kwargs):
#        # POST method
#        form = UserModelForm(request.POST)
#        if form.is_valid():
#            form.save()
#            form = UserModelForm()
#        context = {"form": form}
#        return render(request, self.template_name, context)

class UserRegisterView(View):
    template_name = "user_register.html" #DetailView
        
    def get(self, request, *args, **kwargs):
        # GET method
        form = UserCreateForm()
        context = {"form": form}
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        # POST method
        form = UserCreateForm(request.POST)
        if form.is_valid():
            preForm = form.save(commit=False)
            preForm.funds = user_initial_funds
            print(preForm.funds)
            form = preForm
            form.save()
            auth_login(self.request, form.get_user())
            return redirect('/home/')
        else:
            form = UserCreateForm()
        context = {"form": form}
        return render(request, self.template_name, context)

class LoginView(FormView):
    """
    Provides the ability to login as a user with a username and password
    """
    success_url = '/home/'
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = 'user_login.html'

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        #redirect_to = self.request.REQUEST.get(self.redirect_field_name)
        redirect_to = '/user/user_overview/'
        #if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            #redirect_to = self.success_url
        return redirect_to

class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """
    url = '/home/'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

user/templates/user_history.html
{% extends 'landing.html' %}

{% block content %}
<style>
        * {
          box-sizing: border-box;
        }
        
        /* Create two equal columns that floats next to each other */
        .column {
          float: left;
          width: 20%;
          padding: 10px;
          height: 300px; /* Should be removed. Only for demonstration */
        }
        
        .column1 {
          float: left;
          width: 33%;
          padding: 10px;
          height: 300px; /* Should be removed. Only for demonstration */
        }
        .column2 {
          float: left;
          width: 80%;
          padding: 10px;
          height: 300px; /* Should be removed. Only for demonstration */
        }

        /* Clear floats after the columns */
        .row:after {
          content: "";
          display: table;
          clear: both;
        }
        table {
          border-collapse: collapse;
          width: 100%;
        }
        
        th, td {
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {background-color: #f2f2f2;}
        </style>
<br>

{% if request.user.is_authenticated %}
<div class="row">
    <div class="column1">
        <h1>Bid Offers</h1>
        <table>
            <tr>
                <th>Player</th>
                <th>Value</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
            {% for instance in bid %}
            <tr>
                <td>{{instance.player}}</td>
                <td>$ {{instance.value}}</td>
                <td>{{instance.status}}</td> 
                <td>{{instance.date_updated}}</td>
            </tr>                
            {% endfor %}
        </table>
    </div>
    <div class="column1">
        <h1>Ask Offers</h1>
        <table>
            <tr>
                <th>Player</th>
                <th>Value</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
            {% for instance in ask %}
            <tr>
                <td>{{instance.player}}</td>
                <td>$ {{instance.value}}</td>
                <td>{{instance.status}}</td>
                <td>{{instance.date_updated}}</td>
            </tr> 
            {% endfor %}
        </table>
    </div>
    <div class="column1">
        <h1>IPO Bids</h1>
        <table>
            <tr>
                <th>Player</th>
                <th>Value</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
            {% for instance in bidder %}
            <tr>
                <td>{{instance.ipo}}</td>
                <td>$ {{instance.value}}</td>
                <td>{{instance.status}}</td>  
                <td>{{instance.date_updated}}</td>
            </tr>            
            {% endfor %}
        </table>
    </div>
</div>  
{% else %}
<br>
<br>
<div align="center">
  <h2>You must log in first ...</h2>
</div>
{% endif %}

  


{% endblock content %}

user/templates/user_login.html
{% extends 'landing.html' %}

{% block content %}
<style>
    div{text-align: center;
        align-content: center;}
</style>

{% if request.user.is_authenticated %}
<br>
<br>
<div>
    <h2>You're already logged in ...</h2>
</div>
{% else %}
<br>
<br>
<h1>User login</h1>

<form method='POST'> {% csrf_token %}
    {{form.as_p}}
    <input type='submit' value='Login'>
</form>
{% endif %}
{% endblock content %}

user/templates/user_overview.html
{% extends 'landing.html' %}

{% block content %}
<style>
        * {
          box-sizing: border-box;
        }
        
        /* Create two equal columns that floats next to each other */
        .column {
          float: left;
          width: 20%;
          padding: 10px;
          height: 300px; /* Should be removed. Only for demonstration */
        }
        
        .column1 {
          float: left;
          width: 33%;
          padding: 10px;
          height: 300px; /* Should be removed. Only for demonstration */
        }
        .column2 {
          float: left;
          width: 80%;
          padding: 10px;
          height: 300px; /* Should be removed. Only for demonstration */
        }

        /* Clear floats after the columns */
        .row:after {
          content: "";
          display: table;
          clear: both;
        }
        table {
          border-collapse: collapse;
          width: 100%;
        }
        
        th, td {
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {background-color: #f2f2f2;}
        </style>

{% if request.user.is_authenticated %}
<div class="row">
        <div class="column">
            <br>
            <br>
            <h4>{{request.user.username|capfirst}}</h4>
            <h4>{{request.user.first_name|capfirst}}</h4>
            <h4>{{request.user.last_name|capfirst}}</h4>
            <h4>$ {{request.user.funds}}</h4>
            <h4><a href="/user/user_history/">Trade History</a></h4>
    </div>
    <div class="column2">
        <div><h1>Portfolio</h1></div>
        <div>
            <table>
                <tr>
                    <th>Name</th>
                    <th>Quantity</th>
                    <th>Compromised</th>
                    <th>Total Value</th>
                    <th>Actual Price</th>
                    <th>Last Price</th>
                    <th>Variation</th>
                </tr>
                {% for instance in portfolio %}
                <tr>
                    <td>{{instance.player}}</td>
                    <td>{{instance.count}}</td>
                    <td>{{instance.compromised}}</td>
                    <td>$ {{instance.get_value_total}}</td>
                    <td>$ {{instance.get_value_actual}}</td>
                    <td>$ {{instance.get_value_last}}</td>
                    {% if instance.get_value_actual == instance.get_value_last %}
                    <td style="color:blue">{{instance.get_value_percentege}} %</td>
                    {% elif instance.get_value_actual > instance.get_value_last %}
                    <td style="color:green">{{instance.get_value_percentege}} %</td>
                    {% else %}
                    <td style="color: red">{{instance.get_value_percentege}} %</td>
                    {% endif %}
                </tr> 
                {% endfor %}
            </table>
        </div>
    </div>
    </div>
    <div class="row">
            <div class="column1">
                <h1>Bid Offers</h1>
                <table>
                    <tr>
                        <th>Player</th>
                        <th>Value</th>
                        <th>Status</th>
                        <th>Options</th>
                    </tr>
                    {% for instance in bid %}
                    {% if instance.status == 'Set' %}
                    <tr>
                        <td>{{instance.player}}</td>
                        <td>$ {{instance.value}}</td>
                        <td>{{instance.status}}</td> 
                        <td>
                            <a href="/trade/{{instance.id}}/bid_update/">Edt</a>
                            <a href="/trade/{{instance.id}}/bid_delete/">Del</a>
                        </td>
                    </tr>  
                    {% endif %}                
                    {% endfor %}
                </table>
            </div>
            <div class="column1">
                <h1>Ask Offers</h1>
                <table>
                    <tr>
                        <th>Player</th>
                        <th>Value</th>
                        <th>Status</th>
                        <th>Options</th>
                    </tr>
                    {% for instance in ask %}
                    {% if instance.status == 'Set' %}
                    <tr>
                        <td>{{instance.player}}</td>
                        <td>$ {{instance.value}}</td>
                        <td>{{instance.status}}</td>
                        <td>
                            <a href="/trade/{{instance.id}}/ask_update/">Edt</a>
                            <a href="/trade/{{instance.id}}/ask_delete/">Del</a>
                        </td>
                    </tr> 
                    {% endif %}
                    {% endfor %}
                </table>
            </div>
            <div class="column1">
                <h1>IPO Bids</h1>
                <table>
                    <tr>
                        <th>Player</th>
                        <th>Value</th>
                        <th>Status</th>
                        <th>Options</th>
                    </tr>
                    {% for instance in bidder %}
                    {% if instance.status == 'Set'  %}
                    <tr>
                        <td>{{instance.ipo}}</td>
                        <td>$ {{instance.value}}</td>
                        <td>{{instance.status}}</td>  
                        <td>
                            <a href="/ipo/{{instance.id}}/ipo_update/">Edt</a>
                            <a href="/ipo/{{instance.id}}/ipo_delete/">Del</a>
                        </td>
                    </tr> 
                    {% endif %}                
                    {% endfor %}
                </table>
            </div>
        </div>
{% else %}
<br>
<br>
<div align="center">
        <h2>You must log in first ...</h2>
      </div>
{% endif %}

    


{% endblock content %}

user/templates/user_register.html
{% extends 'landing.html' %}
{% block content %}
{% if request.user.is_authenticated %}
<br>
<br>
<div align="center">
        <br>
        <h2>You're already registered...</h2>
    </div> 
{% else %}
<style>
        div.a {
          line-height: 30%;
          font-size: 12px;
        }
</style>
<h1>User Registration</h1>
<br>
<form method='POST'> {% csrf_token %}
        <div>
        
                <label for="id_username">Username:</label> 
                <input type="text" name="username" maxlength="150" autofocus required id="id_username"> 
                <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
        
        </div>
        <div>
        
                <label for="id_first_name">First name:</label> 
                <input type="text" name="first_name" required id="id_first_name">
        
        </div>
        <div>
        
                    <label for="id_last_name">Last name:</label> 
                    <input type="text" name="last_name" required id="id_last_name">
            
        </div>
        <div>
            
                    <label for="id_email">Email:</label> 
                    <input type="email" name="email" required id="id_email">
            
        </div>
        <div>
            
                    <label for="id_age">Age:</label> 
                    <input type="number" name="age" required id="id_age">
            
        </div>
        <br>
        <div>
        
            <label for="id_password1">Password:</label> 
            <input type="password" name="password1" required id="id_password1"> 
            <div class="a">
                <p>Your password can&#39;t be too similar to your other personal information.</p>
                <p>Your password must contain at least 8 characters.</p>
                <p>Your password can&#39;t be a commonly used password.</p>
                <p>Your password can&#39;t be entirely numeric.</p>
            </div>
        </div>
        <div>
            <label for="id_password2">Password confirmation:</label> 
            <input type="password" name="password2" required id="id_password2"> 
            <div class="a">
                <p>Enter the same password as before, for verification.</p>
            </div>
            <input type="hidden" name="funds" id="id_funds">
        </div>
    <br>
        <div>
            <input type='submit' value='Register'>
        </div>
    </form> 
{% endif %}
{% endblock content %}